[package]
name = "nightcycle/package"
description = "A package!"
version = "0.1.0"
authors = [ "CJ Oyer <coyer@nightcycle.us>",]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = [ "Packages", ".vscode",]

[dependencies]
Maid = "nightcycle/maid@1.1.4"
CompressionUtil = "nightcycle/compression-util@4.1.1"
Signal = "nightcycle/signal@1.0.2"
TableUtil = "nightcycle/table-util@1.1.0"
ServiceProxy = "nightcycle/service-proxy@1.0.0"
MockDataStoreService = "buildthomas/mockdatastoreservice@1.0.3"
MockMessagingService = "nightcycle/mock-messaging-service@1.0.1"
Queue = "nightcycle/queue@2.2.0"
TestEZ = "roblox/testez@0.4.1"
